name: Deploy to Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            DEPLOY_DIR=/var/www/staff
            
            mkdir -p "$DEPLOY_DIR"

            echo "Navigating to project directory..."
            cd "$DEPLOY_DIR"
            
            echo "Pulling latest changes from main..."
            git pull origin main
            
            echo "Installing dependencies..."
            pnpm install --frozen-lockfile
            
            echo "Building project..."
            pnpm exec nx build dashboard-api --configuration=production
            
            echo "Restarting application with PM2..."
            pm2 restart staff || pm2 start dist/apps/dashboard-api/main.js --name staff
            
            echo "Deployment completed successfully!"